### ISSUE TITLE
Refractor + new feature

### ISSUE THREAD

**Issue by v-dawg** [Zwambro/iw4madmin-plugin-iw4todiscord#4]
Hey, I would like to add a feature, which send filtered messages to a channel. 
The use case would be to filter out exodus users and messages calling out cheaters.

For that I first want to refractor the script a bit and for example replace the `var` keywords with `const` or `let`.
So is there a reason why you use var? I cannot test the script myself, as I am not the owner or a power admin of the servers I moderate.
And do you want such a feature?

**Comment by Zwambro** [comment]
> 

Sure, I want that, the code is yours
